### PR TITLE
PKI messages in CMP namespace

### PR DESCRIPTION
**Pull request by felix**
There are a lot of different types of PKI messages. I have started with the basic PKI header and body schemas as well as the CertReqMsg schema used by at least 5 of the PKI body choices.

Comments welcome.

### CODE REVIEW

**Comment by YuryStrozhevsky** [comment]
For the moment I am busy with other activities and will take a look closely at this commit from about one week. Now I have just few question:
1) Why you need "in_window.org.pkijs.getInfoTypeByOID"? I can find out a place with any call to the function?
2) Why you need all these new OIDs and algorithm names? I also can not find any places where it was used.

**Comment by felix** [comment]
1. getInfoTypeByOID is just a helper function like the other OID lookup functions to match OIDs referenced in RFC4210. Not necessary, simply a helper. This function is being used in our local project.
2. As in point 1, they are used in our local project. They are also OIDs referenced in RFCs such as PasswordBasedMac {1 2 840 113533 7 66 13} from http://tools.ietf.org/html/rfc4211#appendix-B

**Comment by YuryStrozhevsky** [comment]
I need to prevent you from moving to "common.js" the "all the stuff we need in our projects". This file is common for ASN1js and PKIjs project and need to be edited very carefully. For example you put additional algos into "getAlgorithmByOID". But seems to forget to check what the function about. As stated in function description the function is "Get WebCrypto algorithm by wel-known OID". None of your algorithms are implemented in WebCrypto standard. 
As a conclusion I think that all your changes should be removed from "common.js". Please consider to move "getInfoTypeByOID" into "cmp_simpl.js", for example.

**Comment by felix** [comment]
Sounds reasonable, files updated.

**Comment by YuryStrozhevsky** [comment]
Also question: why you need to have "*nix-like" line end-ups? Any issues with Windows-like?

**Comment by felix** [comment]
Because I don't use Windows.

**Comment by YuryStrozhevsky** [comment]
OK, I see :) But I do use Windows and then I will keep Windows-like line endings.

**Pull request closed without merging**
